import type { AnalysisResult } from "../types/analysis";

export const mockAnalysis: AnalysisResult = {
  schemaVersion: "analysis.v2",
  taskId: "task_mock",
  versionId: "ver_001",
  inputAsset: {
    assetId: "asset_mock",
    taskId: "task_mock",
    path: "samples/sample-funk-01.wav",
    type: "audio",
    durationSec: 32.4,
    sampleRate: 44100,
    channels: 1,
    sourceLabel: "sample-funk-01.wav",
    metadata: {
      sourceName: "sample-funk-01.wav",
    },
  },
  stemCandidate: {
    stemId: "stem_mock",
    taskId: "task_mock",
    versionId: "ver_001",
    sourceAssetId: "asset_mock",
    stemType: "other",
    path: "output/separated/mock/other.wav",
    durationSec: 32.4,
    qualityScore: 0.8,
    selectionReason: "mock_preview",
  },
  timingGrid: {
    timingGridId: "grid_mock",
    taskId: "task_mock",
    versionId: "ver_001",
    sourceStemId: "stem_mock",
    tempo: 96,
    selectedTimeSignature: "4/4",
    timeSignatureCandidates: ["4/4"],
    beats: [0, 0.625, 1.25, 1.875, 2.5, 3.125, 3.75, 4.375],
    downbeats: [0, 2.5],
    measures: [
      {
        index: 0,
        start: 0,
        end: 2.5,
      },
      {
        index: 1,
        start: 2.5,
        end: 5.0,
      },
    ],
    grooveLabel: "straight",
    confidence: 0.8,
  },
  notationCandidate: {
    notationId: "notation_mock",
    taskId: "task_mock",
    versionId: "ver_001",
    timingGridId: "grid_mock",
    noteIds: ["n1", "n2", "n3"],
    tabRepresentation: {
      tuning: [64, 59, 55, 50, 45, 40],
    },
    staffRepresentation: {
      clef: "treble",
    },
  },
  sourceName: "sample-funk-01.wav",
  durationSec: 32.4,
  bpm: 96,
  timeSignature: {
    numerator: 4,
    denominator: 4,
  },
  beats: [0, 0.625, 1.25, 1.875, 2.5, 3.125, 3.75, 4.375],
  measures: [
    {
      index: 0,
      start: 0,
      end: 2.5,
    },
    {
      index: 1,
      start: 2.5,
      end: 5.0,
    },
  ],
  detailedNotes: [
    {
      noteId: "n1",
      id: "n1",
      taskId: "task_mock",
      versionId: "ver_001",
      start: 0.45,
      end: 0.72,
      midiPitch: 64,
      durationBeats: 0.5,
      measureIndex: 0,
      beatOffset: 0.75,
      noteClass: "backbone",
      stringCandidate: 2,
      fretCandidate: 5,
    },
    {
      noteId: "n2",
      id: "n2",
      taskId: "task_mock",
      versionId: "ver_001",
      start: 0.82,
      end: 1.18,
      midiPitch: 66,
      durationBeats: 0.5,
      measureIndex: 0,
      beatOffset: 1.25,
      noteClass: "backbone",
      stringCandidate: 2,
      fretCandidate: 7,
    },
    {
      noteId: "n3",
      id: "n3",
      taskId: "task_mock",
      versionId: "ver_001",
      start: 1.3,
      end: 1.9,
      midiPitch: 69,
      durationBeats: 1,
      measureIndex: 0,
      beatOffset: 2,
      noteClass: "backbone",
      stringCandidate: 1,
      fretCandidate: 5,
    },
  ],
  notes: [
    {
      noteId: "n1",
      id: "n1",
      taskId: "task_mock",
      versionId: "ver_001",
      start: 0.45,
      end: 0.72,
      midiPitch: 64,
      durationBeats: 0.5,
      measureIndex: 0,
      beatOffset: 0.75,
      noteClass: "backbone",
      stringCandidate: 2,
      fretCandidate: 5,
    },
    {
      noteId: "n2",
      id: "n2",
      taskId: "task_mock",
      versionId: "ver_001",
      start: 0.82,
      end: 1.18,
      midiPitch: 66,
      durationBeats: 0.5,
      measureIndex: 0,
      beatOffset: 1.25,
      noteClass: "backbone",
      stringCandidate: 2,
      fretCandidate: 7,
    },
    {
      noteId: "n3",
      id: "n3",
      taskId: "task_mock",
      versionId: "ver_001",
      start: 1.3,
      end: 1.9,
      midiPitch: 69,
      durationBeats: 1,
      measureIndex: 0,
      beatOffset: 2,
      noteClass: "backbone",
      stringCandidate: 1,
      fretCandidate: 5,
    },
  ],
};
